#!/bin/bash
apt-get update
apt-get upgrade
sudo apt install systemctl
#docker
sudo apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
sudo systemctl status docker
#docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
#zabbix install
cd /opt/
git clone https://github.com/zabbix/zabbix-docker
docker-compose -f ./zabbix-docker/docker-compose_v3_alpine_mysql_latest.yaml up -d
docker ps -a
#ip
hostname -I
